### ISSUE TITLE
ERROR: Could not determine sun times for coordinates

### ISSUE THREAD

**Issue by jonhosmer** [allspiritseve/sun#1]
When attempting to get the `solar_noon` for a set of coordinates for any date (tried several different days), I get this error:
```
time = Date.parse('Tue, 10 Dec 2019')
latitude = 71.706936
longitude = -42.604303
Sun.solar_noon(time, latitude, longitude)

Sun::InvalidCoordinates: Could not determine sun times for coordinates: 71.706936, -42.604303
	from /Users/j/git/sun/lib/sun.rb:89:in `rescue in sun_time_minutes'
	from /Users/j/git/sun/lib/sun.rb:85:in `sun_time_minutes'
	from /Users/j/git/sun/lib/sun.rb:80:in `sun_time'
	from /Users/j/git/sun/lib/sun.rb:27:in `solar_noon'
	from (irb):60
	from ./bin/console:14:in `<main>'
```

It appears to be caused by https://github.com/allspiritseve/sun/blob/master/lib/sun.rb#L170 (`Math.acos` in the `hour_angle` function).  It is attempting to get the `acos` of `1.224998156724628` which results in a `Math::DomainError` (`Numerical argument is out of domain - "acos"`).

**Comment by allspiritseve** [comment]
Hey Jon, I'm using [NOAA's solar equations](https://www.esrl.noaa.gov/gmd/grad/solcalc/), and it looks like they aren't able to calculate a valid sunrise / sunset for those coordinates (which is somewhere in Greenland?)

However, they did seem to calculate solar noon, so I checked the code and the `hour_angle` method is where the exception is occurring, and solar noon multiplies it by 0, so I just pushed an update that avoids calculating `hour_angle` for solar noon. That should fix the exception you were getting.

**Comment by jonhosmer** [comment]
Nice, thanks so much Cory!
